/**
 * Centralized Event Definitions
 * Single source of truth for all system events
 */

export const EVENTS = {
  COMMAND: {
    START_BATCH: 'COMMAND.START_BATCH',
    STOP_BATCH: 'COMMAND.STOP_BATCH',
    UPLOAD_FILE: 'COMMAND.UPLOAD_FILE',
    TOGGLE_TEST_MODE: 'COMMAND.TOGGLE_TEST_MODE',
    CREATE_INVOICE: 'COMMAND.CREATE_INVOICE',
    UPDATE_INVOICE: 'COMMAND.UPDATE_INVOICE',
    DELETE_INVOICE: 'COMMAND.DELETE_INVOICE',
    VOID_INVOICE: 'COMMAND.VOID_INVOICE',
    CLEAR_DATA_FOR_PLATFORM_SWITCH: 'COMMAND.CLEAR_DATA_FOR_PLATFORM_SWITCH',
    UPDATE_BUTTON_STATE: 'COMMAND.UPDATE_BUTTON_STATE',
    FETCH_DATA_SOURCE: 'COMMAND.FETCH_DATA_SOURCE',
    FETCH_CARRIER_CONFIG: 'COMMAND.FETCH_CARRIER_CONFIG'
  },

  PROCESS: {
    INVOICE_CREATING: 'PROCESS.INVOICE_CREATING',
    INVOICE_CREATED: 'PROCESS.INVOICE_CREATED',
    INVOICE_VOIDING: 'PROCESS.INVOICE_VOIDING',
    INVOICE_VOIDED: 'PROCESS.INVOICE_VOIDED',
    INVOICE_QUERYING: 'PROCESS.INVOICE_QUERYING',
    INVOICE_QUERIED: 'PROCESS.INVOICE_QUERIED',
    ALLOWANCE_CREATING: 'PROCESS.ALLOWANCE_CREATING',
    ALLOWANCE_CREATED: 'PROCESS.ALLOWANCE_CREATED',
    BATCH_STARTED: 'PROCESS.BATCH_STARTED',
    ROW_PROCESSING: 'PROCESS.ROW_PROCESSING',
    ROW_SUCCESS: 'PROCESS.ROW_SUCCESS',
    ROW_FAILED: 'PROCESS.ROW_FAILED',
    PROGRESS_UPDATE: 'PROCESS.PROGRESS_UPDATE',
    BATCH_COMPLETED: 'PROCESS.BATCH_COMPLETED',
    BATCH_ABORTED: 'PROCESS.BATCH_ABORTED',
    BATCH_PAUSED: 'PROCESS.BATCH_PAUSED',
    FETCH_STARTED: 'PROCESS.FETCH_STARTED',
    FETCH_COMPLETED: 'PROCESS.FETCH_COMPLETED',
    FETCH_ABORTED: 'PROCESS.FETCH_ABORTED'
  },


  PLATFORM: {
    INVOICE_CREATING: 'PLATFORM.INVOICE_CREATING',
    INVOICE_CREATED: 'PLATFORM.INVOICE_CREATED',
    INVOICE_ERROR: 'PLATFORM.INVOICE_ERROR',
    INVOICE_VOIDING: 'PLATFORM.INVOICE_VOIDING',
    INVOICE_QUERYING: 'PLATFORM.INVOICE_QUERYING',
    INVOICE_ALLOWANCE: 'PLATFORM.INVOICE_ALLOWANCE',
    INVOICE_PROCESS: 'PLATFORM.INVOICE_PROCESS',
    CREATION_FAILED: 'PLATFORM.CREATION_FAILED',
    CREDENTIALS_LOADED: 'PLATFORM.CREDENTIALS_LOADED',
    CREDENTIALS_REQUESTED: 'PLATFORM.CREDENTIALS_REQUESTED',
    CREDENTIALS_RESPONSE: 'PLATFORM.CREDENTIALS_RESPONSE'
  },

  DATA: {
    INVOICE_DATA_PREPARED: 'DATA.INVOICE_DATA_PREPARED',
    RESPONSE_RECEIVED: 'DATA.RESPONSE_RECEIVED',
    PAYLOAD_VALIDATED: 'DATA.PAYLOAD_VALIDATED',
    RESULT_FORMATTED: 'DATA.RESULT_FORMATTED',

    INVOICE_DATA_PROVIDED: 'DATA.INVOICE_DATA_PROVIDED',
    ADD_INVOICE_COMPLETED: 'DATA.ADD_INVOICE_COMPLETED',
    UPDATE_INVOICE_COMPLETED: 'DATA.UPDATE_INVOICE_COMPLETED',
    UPDATE_INVOICE_STATUS_COMPLETED: 'DATA.UPDATE_INVOICE_STATUS_COMPLETED',
    DELETE_INVOICE_COMPLETED: 'DATA.DELETE_INVOICE_COMPLETED',
    ALL_INVOICES_PROVIDED: 'DATA.ALL_INVOICES_PROVIDED',
    CLEAR_ALL_DATA_COMPLETED: 'DATA.CLEAR_ALL_DATA_COMPLETED',
    INVOICE_COUNT_PROVIDED: 'DATA.INVOICE_COUNT_PROVIDED',
    PLATFORM_CONFIG_PROVIDED: 'DATA.PLATFORM_CONFIG_PROVIDED',
    SET_INVOICES_COMPLETED: 'DATA.SET_INVOICES_COMPLETED',
    STORE_PLATFORM_CONFIG_COMPLETED: 'DATA.STORE_PLATFORM_CONFIG_COMPLETED'
  },

  UI: {
    UPDATE_BUTTON: 'UI.UPDATE_BUTTON',
    ADD_INVOICE_CLICKED: 'UI.ADD_INVOICE_CLICKED',
    UPLOAD_CLICKED: 'UI.UPLOAD_CLICKED',
    EXECUTE_CLICKED: 'UI.EXECUTE_CLICKED',
    STOP_CLICKED: 'UI.STOP_CLICKED',
    ADD_ITEM_CLICKED: 'UI.ADD_ITEM_CLICKED',
    MORE_ACTIONS_CLICKED: 'UI.MORE_ACTIONS_CLICKED',
    DOWNLOAD_CLICKED: 'UI.DOWNLOAD_CLICKED',
    CLEAR_DATA_CLICKED: 'UI.CLEAR_DATA_CLICKED',

    FILTER_CHANGED: 'UI.FILTER_CHANGED',
    FILE_SELECTED: 'UI.FILE_SELECTED',
    TABLE_ACTION_CLICKED: 'UI.TABLE_ACTION_CLICKED',
    STATE_CHANGED: 'UI.STATE_CHANGED',
    CARRIER_DESCRIPTION_REQUESTED: 'UI.CARRIER_DESCRIPTION_REQUESTED',
    CARRIER_DESCRIPTION_RESOLVED: 'UI.CARRIER_DESCRIPTION_RESOLVED'

  },

  APP: {
  },

  FORM: {
    CATEGORY_CHANGED: 'FORM.CATEGORY_CHANGED'
  },

  DIALOG: {
    CARRIER_CONFIG_SYNC: 'DIALOG.CARRIER_CONFIG_SYNC',
    CARRIER_CONFIG_REQUESTED: 'DIALOG.CARRIER_CONFIG_REQUESTED'
  },

  ERROR: {
    PROCESSING_FAILED: 'ERROR.PROCESSING_FAILED',
    PLATFORM_ERROR: 'ERROR.PLATFORM_ERROR',
    VALIDATION_FAILED: 'ERROR.VALIDATION_FAILED'
  },

  DOMAIN: {
    INVOICE_ADDED: 'DOMAIN.INVOICE_ADDED',
    INVOICE_UPDATED: 'DOMAIN.INVOICE_UPDATED',
    INVOICE_DELETED: 'DOMAIN.INVOICE_DELETED',
    DATA_CHANGED: 'DOMAIN.DATA_CHANGED',
    DATA_IMPORTED: 'DOMAIN.DATA_IMPORTED',
    STATISTICS_CHANGED: 'DOMAIN.STATISTICS_CHANGED',
    DIALOG_SHOW_REQUESTED: 'DOMAIN.DIALOG_SHOW_REQUESTED',
    CONFIRMATION_REQUESTED: 'DOMAIN.CONFIRMATION_REQUESTED',
    ALERT_REQUESTED: 'DOMAIN.ALERT_REQUESTED',
  },

  APP_EVENTS: {
    PLATFORM_CHANGED: 'APP_EVENTS.PLATFORM_CHANGED',
    TEST_MODE_TOGGLED: 'APP_EVENTS.TEST_MODE_TOGGLED',
    BUTTON_STATE_CHANGED: 'APP_EVENTS.BUTTON_STATE_CHANGED',
    SCROLL_STATE_CHANGED: 'APP_EVENTS.SCROLL_STATE_CHANGED'
  }
};

const moduleEvents = new Map();
const dynamicEvents = new Set();

const ALLOWED_MODULE_CATEGORIES = [
  'UI',
  'ACTION',
  'VALIDATE',
  'TRANSFORM',
  'NOTIFY'
];
